spring.application.name=ani-sync-service
server.port=8081

# 默认激活 H2 配置
spring.profiles.active=${DB_PROFILE:h2}

# Sa-Token 配置
# token 名称（同时也是 cookie 名称）
sa-token.token-name=ani-link-token
# token 有效期（单位：秒） 默认30天，-1 代表永久有效
sa-token.timeout=2592000
# token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
sa-token.active-timeout=-1
# 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
sa-token.is-concurrent=true
# 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
sa-token.is-share=false
# token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
sa-token.token-style=uuid
# 是否输出操作日志 
sa-token.is-log=true

# 媒体附属数据根目录（可通过容器环境变量 MEDIA_DATA_DIR 覆盖）
media.data.root-dir=${MEDIA_DATA_DIR:./data/media-data}

# 字幕抽取输出目录（可通过容器环境变量 SUBTITLE_DIR 覆盖）
media.subtitle.output-dir=${SUBTITLE_DIR:${media.data.root-dir}/subtitles}

# 缩略图输出目录（可通过容器环境变量 THUMBNAIL_DIR 覆盖）
media.thumbnail.output-dir=${THUMBNAIL_DIR:${media.data.root-dir}/thumbnails}