# .github/workflows/cicd.yml

name: package and push docker

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Build frontend
      run: |
        cd ui
        pnpm install
        pnpm run build

    - name: Copy frontend build to backend static resources
      run: |
        mkdir -p api/src/main/resources/static
        cp -r ui/dist/* api/src/main/resources/static/

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build backend with Maven
      run: |
        cd api
        mvn clean package

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker image
      run: docker build -t ezsky333/anilinkserver .

    - name: Push Docker image to Docker Hub
      run: docker push ezsky333/anilinkserver

    - name: Logout of Docker Hub
      run: docker logout
